services:
  mariadb:
    container_name: incep-mariadb
    build: requirements/mariadb/
    volumes:
      - type: volume
        source: db-volume
        target: /home/owatanab/data
    env_file:
      - .env
    networks:
      - db-network
    restart: on-failure

  nginx:
    container_name: incep-nginx
    build: requirements/nginx/
    volumes:
      - type: volume
        source: wordpress-volume
        target: /home/owatanab/data
        read_only: true
    networks:
      - wp-network
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: on-failure

  wordpress:
    container_name: incep-wordpress
    build: requirements/wordpress/
    volumes:
      - type: volume
        source: wordpress-volume
        target: /home/owatanab/data
    networks:
      - wp-network
      - db-network
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure

volumes:
  db-volume:
  wordpress-volume:

networks:
  wp-network:
    driver: bridge
  db-network:
    driver: bridge